- frontend/src/Commits/DiffPanel.react.tsx
> UTF hellip is not displayed correctly

- plugins/versionpress/tests/LoadTests/CommitterTest.php
> CommitterTest now runs from any directory

- plugins/versionpress/src/Database/wordpress-schema.yml
Resolves #885 .
Reviewers:
Thank you.
> Fixed mapping of default_category and default_link_category

- plugins/versionpress/src/Database/wordpress-schema.yml
> Support for menu with automatically added pages

- plugins/versionpress/src/Database/WpdbMirrorBridge.php
Resolves #900 .
Please review:
Thank you.
> Insert data used should be merged with database for versioning

- plugins/versionpress/src/Storages/Serialization/IniSerializer.php
- plugins/versionpress/tests/Unit/IniSerializerTest.php
> Changing order of rows for serialized options

- plugins/versionpress/src/Storages/UserStorage.php
- plugins/versionpress/tests/StorageTests/UserStorageTest.php
Resolves #901.
Please review:
Thank you.
> `user_activation_key` as unwanted column.

- plugins/versionpress/src/Cli/vp-internal.php
- plugins/versionpress/src/Database/Database.php
- plugins/versionpress/src/Database/VpidRepository.php
- plugins/versionpress/src/Database/WpdbMirrorBridge.php
- plugins/versionpress/src/Initialization/Initializer.php
- plugins/versionpress/src/Storages/CommentStorage.php
- plugins/versionpress/src/Synchronizers/SynchronizerBase.php
- plugins/versionpress/src/Utils/WordPressCacheUtils.php
- plugins/versionpress/tests/StorageTests/CommentStorageTest.php
- plugins/versionpress/tests/SynchronizerTests/Utils/WpdbCopy.php
- plugins/versionpress/tests/Utils/DBAsserter.php
- plugins/versionpress/versionpress.php
Resolves #903 .
Reviewers:
Thank you.
> Database and Storage does not match when VP is deactivated

- plugins/versionpress/src/Git/MergeDriverInstaller.php
Resolves #876.
PHP binary is now detected from `extension_dir` rather than `PHP_BINARY` which is not set for requests running through a web server. `extension_dir` is a workaround but should be quite reliable on Windows, and Windows is the only OS where we need this workaround (Linux and Mac OS use Bash merge driver).
Reviewers:
> PHP_BINARY fix

- plugins/versionpress/src/Database/VpidRepository.php
Resolves #929 .
Reviewers:
Thank you.
> Delete query fails when deleting `id`

- frontend/src/Commits/revertDialog.tsx
- frontend/src/ServicePanel/ServicePanel.react.tsx
Resolves #786.
Updated EAP notices in the frontend project.
Reviewers:
> Update EAP notices to 'Early Access'

- plugins/versionpress/admin/public/css/popover-custom.css
- plugins/versionpress/admin/public/css/style.css
> Wrong padding in a warning popover

- plugins/versionpress/src/Database/EntityInfo.php
- plugins/versionpress/src/Database/schema-readme.md
- plugins/versionpress/src/Database/wordpress-schema.yml
- plugins/versionpress/src/Storages/DirectoryStorage.php
- plugins/versionpress/src/Storages/PostStorage.php
- plugins/versionpress/src/Storages/UserStorage.php
- plugins/versionpress/src/Synchronizers/PostsSynchronizer.php
- plugins/versionpress/src/Synchronizers/SynchronizerBase.php
- plugins/versionpress/tests/Unit/EntityInfoTest.php
Resolves #902 .
How to define ignored columns is described in file `schema-readme.md`
Reviewers:
> Enable column ignoring

- gulpfile.js
> `core.filemode` set to false in `gulp git-config`

- plugins/versionpress/admin/inc/javascriptGui.php
- plugins/versionpress/versionpress.php
> Use current VP version for enqueuing styles and scripts

- frontend/src/Commits/CommitsTable.react.tsx
- plugins/versionpress/src/Api/VersionPressApi.php
- plugins/versionpress/src/Git/GitRepository.php
> Old commits not ignored when searching

- plugins/versionpress/src/ChangeInfos/Sorting/SortingStrategy.php
- plugins/versionpress/tests/End2End/Utils/PostTypeTestCase.php
- plugins/versionpress/tests/Selenium/ActivationDeactivationTest.php
- plugins/versionpress/tests/test-config.sample.yml
> WordPress 4.5 compatibility

- plugins/versionpress/tests/Selenium/ActivationDeactivationTest.php
- plugins/versionpress/uninstall.php
Resolves #949 .
Please review:
Thank you.
> Fix of complete deactivation test

- plugins/versionpress/src/Api/VersionPressApi.php
Resolves #941.
The original code was absolutely wrong. Now it splits the full diff to individual files, detects parents for meta entities and passes correct data structure to the `SynchronizationProcess`.
Reviewers:
> Fixed synchronization of manually committed entities

- plugins/versionpress/src/Storages/CommentStorage.php
Resolves #954 .
Reviewers:
Thank you
> Failing comment trashing

- plugins/versionpress/tests/End2End/Menus/MenusSeleniumWorker.php
> Failing menu edit test fix

- plugins/versionpress/src/Database/schema-readme.md
Resolves #933.
Only stylistic updates, no technical change, but quite a few changes.
Reviewers:
> Schema README review

- plugins/versionpress/composer.json
- plugins/versionpress/composer.lock
> Code Sniffer moved to dev dependencies

- plugins/versionpress/src/ChangeInfos/ChangeInfoEnvelope.php
- plugins/versionpress/src/VersionPress.php
> Fixed comments referencing 'master'

- .travis.yml
- plugins/versionpress/src/Cli/vp-internal.php
> Travis script for checking the code style

- .ide-tpl/.idea-versionpress/codeStyleSettings.xml
- docs/Dev-Setup.md
Resolves #629.
PhpStorm project files and Dev-Setup update.
Reviewers:
> Small codestyle settings updates

- plugins/versionpress/admin/inc/javascriptGui.php
> Change GUI data source base url from home to site.

- plugins/versionpress/src/Initialization/WpConfigSplitter.php
> Moving VP constants to the common config on initialization

- plugins/versionpress/src/Cli/vp.php
> Fixed path computation + validation in `wp vp config`

- plugins/versionpress/src/Utils/SystemInfo.php
Resolves #966.
Please review:
Thank you
> Added options `home` and `siteurl` to system-info output.

- plugins/versionpress/tests/Unit/WpConfigSplitterTest.php
Resolves #953 .
Reviewers:
thank you.
> Fixed test of WpConfigSplitter

- plugins/versionpress/bootstrap.php
- plugins/versionpress/src/Api/VersionPressApi.php
- plugins/versionpress/src/ChangeInfos/UntrackedChangeInfo.php
- plugins/versionpress/src/DI/DIContainer.php
- plugins/versionpress/src/Git/CommitMessage.php
> VP prefix is stripped when commit message is displayed to user

- plugins/versionpress/src/Cli/vp.php
Resolves #989 .
Tested on local environment and workshop site.
Reviewers:
> Fix of site restore when cloning via wp-cli.

- plugins/versionpress/setup-hooks.php
- plugins/versionpress/versionpress.php
> Fixed using __FILE__ constant in setup-hooks.php

- plugins/versionpress/src/Api/VersionPressApi.php
> Overview panel displays changed INI files if WordPress is in directory

- plugins/versionpress/src/Cli/vp.php
> Fix of wp vp config

- plugins/versionpress/src/Git/MergeDriverInstaller.php
- plugins/versionpress/src/Utils/PathUtils.php
- plugins/versionpress/tests/Unit/RelativePathsTest.php
> Wrong path in `.gitattributes`

- plugins/versionpress/src/Utils/FileSystem.php
Resolves #945 .
I've removed method `FileSystem::possiblyFixGitPermissions`. Please review and test if it works.
Reviewers:
Thank you.
> Change dir permissions fix

- frontend/src/services/WpApi.ts
> Prevent caching of REST API requests

- plugins/versionpress/tests/gulpfile.js
Resolves #1057 .
Selenium version updated to `2.53.0`
Reviewers:
Thank you.
> Update of Selenium version

- frontend/src/pages/HomePage.react.tsx
Resolves #984.
Fixed displaying welcome panel.
Reviewers:
> Make AJAX work with PHP error / notice output

- docs/Dev-Setup.md
> Frontend Dev-Setup: update `requireApiAuth` section

- frontend/src/services/WpApi.ts
> Failing frontend build

- frontend/src/BulkActionPanel/BulkActionPanel.react.tsx
- frontend/src/CommitPanel/CommitPanel.react.tsx
- frontend/src/CommitPanel/CommitPanelCommit.react.tsx
- frontend/src/CommitPanel/CommitPanelOverview.react.tsx
- frontend/src/Commits/CommitsTable.react.tsx
- frontend/src/Commits/CommitsTableRow.react.tsx
- frontend/src/Commits/CommitsTableRowDetails.react.tsx
- frontend/src/Commits/revertDialog.tsx
- frontend/src/ServicePanel/ServicePanel.react.tsx
- frontend/src/common/ConfirmDialog.react.tsx
- frontend/src/common/Modal.react.tsx
- frontend/src/common/ProgressBar.react.tsx
- frontend/src/common/portal.tsx
- frontend/src/pages/HomePage.react.tsx
Resolves #1085.
Improved sometimes unclear attribute names in the front end codebase. If you have any suggestion to improve other names, feel free to share them.
Reviewers:
> Improve unclear attribute names

- frontend/src/BulkActionPanel/BulkActionPanel.react.tsx
- frontend/src/CommitPanel/CommitPanel.react.tsx
- frontend/src/CommitPanel/CommitPanelCommit.react.tsx
- frontend/src/CommitPanel/CommitPanelDetails.react.tsx
- frontend/src/CommitPanel/CommitPanelNotice.react.tsx
- frontend/src/CommitPanel/CommitPanelOverview.react.tsx
- frontend/src/Commits/CommitOverview.react.tsx
- frontend/src/Commits/CommitsTable.react.tsx
- frontend/src/Commits/CommitsTableNote.react.tsx
- frontend/src/Commits/CommitsTableRow.react.tsx
- frontend/src/Commits/CommitsTableRowDetails.react.tsx
- frontend/src/Commits/CommitsTableRowSummary.react.tsx
- frontend/src/Commits/DiffPanel.react.tsx
- frontend/src/Commits/revertDialog.tsx
- frontend/src/Filter/Filter.react.tsx
- frontend/src/ServicePanel/ServicePanel.react.tsx
- frontend/src/common/ConfirmDialog.react.tsx
- frontend/src/common/FlashMessage.react.tsx
- frontend/src/common/Modal.react.tsx
- frontend/src/common/ProgressBar.react.tsx
- frontend/src/common/portal.tsx
- frontend/src/main.tsx
- frontend/src/pages/HomePage.react.tsx
- frontend/src/routes.tsx
- frontend/src/services/GitBranchColorProvider.ts
- frontend/src/services/WpApi.ts
- frontend/tslint.json
Resolves #1090 and #1088.
Fixed inconsistent JavaScript function binding by introducing [arrow functions] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). In the process of fixing function binding also introduced [class instance fields](https://github.com/jeffmo/es-class-fields-and-static-properties) for initializing the React.js component's state and fixed inconsistent order of the React.js component’s (life cycle) methods.
Reviewers:
> Use consistent function binding and order of React.js methods

- gulpfile.js
Resolves #1099.
Reviewers:
Thank you.
> Removed ruleset.xml from files included to build process

- .ide-tpl/.idea-versionpress/versionpress.iml
- plugins/versionpress/composer.json
- plugins/versionpress/composer.lock
- plugins/versionpress/tests/SqlTests/SqlQueryParserTest.php
I've noticed you're using uda11/sql-parser, which is no longer maintained, see https://packagist.org/packages/udan11/sql-parser
Reviewers:
> Use phpmyadmin/sql-parser instead of abandoned udan11/sql-parser"

- frontend/src/components/search/modifiers/list/ItemListItem.tsx
- frontend/src/components/search/popup/Popup.less
- plugins/versionpress/src/Utils/QueryLanguageUtils.php
Fixes some UI issues as disabled scrollbars and wrapping long labels in autocomplete component (#805).
Reviewers:
> Autocomplete: UI issues

- plugins/versionpress/src/Utils/AutocompleteUtils.php
> Autocomplete: Capital P, dangit!

- plugins/versionpress/admin/inc/activationPanel.php
> Fix of url params when VP cannot be activated

- frontend/src/components/dialogs/UndoDisabledDialog.tsx
- frontend/src/components/legacy/icons.less
- frontend/src/components/service-panel/Button.tsx
- plugins/versionpress/admin/deactivate.php
- plugins/versionpress/admin/inc/activationPanel.php
- plugins/versionpress/admin/inc/admin.php
- plugins/versionpress/admin/public/icons/style.css
- plugins/versionpress/admin/undo.php
> Fix too unspecific backend CSS selector

- .github/PULL_REQUEST_TEMPLATE.md
> 1160 - new reviewers system

- plugins/versionpress/src/Storages/Serialization/IniSerializer.php
- plugins/versionpress/tests/Unit/IniSerializerTest.php
> [#1161] Fixed handling negative numbers in serialized data

- docs/Plugin-Support.md
Based on feedback in #1155, plus some other improvements.
> Plugin-Support.md updates

- CONTRIBUTING.md
> GitHub Projects added to CONTRIBUTING.md / Our development process

- plugins/versionpress/.versionpress/actions.yml
- plugins/versionpress/.versionpress/hooks.php
> Using post format instead of post type if possible

- plugins/versionpress/src/Storages/Serialization/IniSerializer.php
- plugins/versionpress/src/Utils/StringUtils.php
- plugins/versionpress/tests/GitRepositoryTests/MergeDriverTest.php
- plugins/versionpress/tests/Unit/IniSerializerTest.php
- plugins/versionpress/tests/Unit/IniSerializer_IssueWP284Test.php
- plugins/versionpress/tests/Unit/IniSerializer_IssueWP351Test.php
- plugins/versionpress/tests/Unit/StringUtilsTest.php
> Switch to LF line endings for INI files

- CONTRIBUTING.md
- README.md
- docs/content/en/01-getting-started/15-about-eap.md
- docs/content/en/01-getting-started/_index.md
- frontend/src/components/dialogs/UndoEnabledDialog.tsx
- frontend/src/components/service-panel/panel/Warning.tsx
- plugins/versionpress/admin/inc/activationPanel.php
- plugins/versionpress/admin/inc/admin.php
- plugins/versionpress/admin/undo.php
- plugins/versionpress/setup-hooks.php
Resolves #1201 
Updated docs, READMEs, CONTRIBUTING.md and mentions in the UI.
> 1201 'Early Access' to 'Developer Preview'

- docs/Plugin-Support.md
- plugins/versionpress/.versionpress/hooks.php
- plugins/versionpress/src/ChangeInfos/ChangeInfoFactory.php
- plugins/versionpress/src/ChangeInfos/EntityChangeInfo.php
- plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php
Resolves #1226.
There is a new filter called `vp_action_priority_{$scope}` by which we can dynamically change the priority.
> Custom WPLANG priority

- plugins/versionpress/setup-hooks.php
Resolves #1188
Generate random GUIDs also for attachments (different hook).
> Generate random GUIDs also for attachments

- docs/Plugin-Support.md
- plugins/versionpress/composer.json
- plugins/versionpress/composer.lock
- plugins/versionpress/src/Database/VpidRepository.php
- plugins/versionpress/src/Git/Reverter.php
- plugins/versionpress/src/Storages/Serialization/IniSerializer.php
- plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php
- plugins/versionpress/src/Utils/ReferenceUtils.php
- plugins/versionpress/src/Utils/SerializedDataCursor.php
- plugins/versionpress/tests/Unit/IniSerializerTest.php
- plugins/versionpress/tests/Unit/SerializedDataCursorTest.php
- plugins/versionpress/tests/Unit/VpidRepositoryTest.php
- plugins/versionpress/tests/Utils/ReferenceUtilsTest.php
Resolves #1234
See `Plugin-Support.md` for more info.
> Support serialized data inside serialized data

- plugins/versionpress/.versionpress/schema.yml
Resolves #1169 
Changesets will be ignored for now, we will add support later, see discussion in #1166 (also support for JSON is needed in this case: #1145).
> Ignore changesets for now

- plugins/versionpress/.versionpress/schema.yml
Resolves #1164
Small changes: header video, custom CSS and Twenty Seventeen.
> Schema changes for WordPress 4.7

- plugins/versionpress/.versionpress/schema.yml
Resolves #1217
Define entities in media widgets for WordPress 4.8.
> Media widgets in WP 4.8

- plugins/versionpress/src/Database/WpdbMirrorBridge.php
Resolves #1146
VP now loads the entity from database instead of saving parsed SQL data directly.
Unfortunatelly, I don't know how to test it (automatically). I used following code to test it manually:
```php
if (basename($_SERVER['PHP_SELF']) === 'admin.php') { // to trigger it only on reload, not on every AJAX request
global $wpdb;
$time = time();
$wpdb->query("INSERT INTO wp_commentmeta (comment_id, meta_key, meta_value) VALUES (1, 'vp_test_$time', NOW()), (1, 'vp_test_2_$time', NOW()-1)");
$wpdb->query("INSERT INTO wp_options (option_name, option_value) VALUES ('vp_test_$time', NOW()), ('vp_test_2_$time', NOW()-1)");
}
```
> Saving real values on INSERT

- plugins/versionpress/src/Database/ShortcodesReplacer.php
> Shortcodes without attributes

- plugins/versionpress/.versionpress/hooks.php
Resolves #1195
Ignoring only saves on heartbeat.
> Quick edits for drafts not tracked

- CONTRIBUTING.md
- docs/Development-Process.md
- docs/README.md
Much shorter and less intimidating `CONTRIBUTING.md`, new `Development-Process.md` document where some of the things moved. This also replaces `Issues.md`.
Also resolves #1245.
> Revised CONTRIBUTING.md, new Development-Process.md

- plugins/versionpress/src/Database/VpidRepository.php
> Considering negative numbers as null references

- gulpfile.js
- package.json
> Fix zip compression

- plugins/versionpress/src/Utils/UninstallationUtil.php
> Uninstall utility assumes ChangeInfo type

- plugins/versionpress/src/Database/WpdbMirrorBridge.php
> Deleting M:N references

- docs/Dev-Setup.md
- package.json
> Node 8.1+ and npm 5+ required

- frontend/src/components/search/modifiers/date/adapter.ts
- frontend/src/components/search/modifiers/getAdapter.ts
- frontend/src/components/search/modifiers/list/adapter.ts
Resolves #1267.
There was a problem with `this` in default module export with parameter. Switched the implementation to `class`.
> Search produces a lot of JavaScript errors

- plugins/versionpress/admin/inc/activate.php
- plugins/versionpress/internal-functions.php
- plugins/versionpress/setup-hooks.php
> Applying `vp_entity_should_be_saved_{$entity}` filters on init

- docs/content/en/09-release-notes/71-4.0-beta.md
- docs/content/en/09-release-notes/72-4.0-alpha1.md
> 4.0 beta release notes

- README.md
- dev-env/Dockerfile
- docs/Dev-Setup.md
- frontend/package-lock.json
- package-lock.json
- plugins/versionpress/tests/package-lock.json
Ref: #1263 
Final updates before 4.0-beta release. WIP.
> Pre 4.0-beta polish

- dev-env/Dockerfile
- docs/Dev-Setup.md
- ext-libs/composer.json
- frontend/package-lock.json
- plugins/versionpress/tests/package-lock.json
- plugins/versionpress/tests/test-config.yml
... and other minor updates. No issue.
> WP 4.9 for test sites

- frontend/src/components/commits-table/commit-summary/Checkbox.tsx
> Checkboxes for bulk update should once again be checkable

- ext-libs/composer.lock
- plugins/versionpress/tests/package-lock.json
Follow up to #1307 (should have been part of that).
> More WP 4.9 updates

- plugins/versionpress/admin/inc/activationPanel.php
Small typo in the activation message.
> Typo in the activation message

- frontend/package-lock.json
- frontend/package.json
> Fix frontend package vulnerabilities

- docs/content/en/developer/dev-setup.md
> Slightly updated intro section on Docker

- docs/content/en/getting-started/configuration.md
Introduced in #1187, we forgot to document it.
I've also fixed the Markdown formatting in `configuration.md`.
> Docs for VP_WP_CLI_BINARY config option

- .gitignore
- .vscode/settings.json
Config for these extensions added:
- PHP Tools for VSCode
- Markdown All in One
- Markdownlint
> Added VSCode settings

- plugins/versionpress/src/Initialization/ReplacerMethods.src.php
Fixed wrong SELECT and SHOW queries detection due to leading tabs and spaces.
> Fixed wrong SELECT and SHOW queries detection

- frontend/package-lock.json
A small technical change in the package-lock.json format in recent versions of npm.
> Updated lockfile for npm 6.7

- frontend/package-lock.json
- frontend/package.json
I've updated all npm packages which had some vulnerabilities. All is clean again.
```bash
npm audit
found 0 vulnerabilities
```
> Update frontend dependecies

- docs/content/en/developer/development-process.md
> Small update of release process docs
