plugins/versionpress/src/Database/wordpress-schema.yml
Resolves #865  .
Removing tracking of `default_link_category` from `wordpress-schema.yml`
Reviewers:
Thank you.
=> Disable tracking of `default_link_category`

plugins/versionpress/src/Database/wordpress-schema.yml, plugins/versionpress/src/Storages/CommentStorage.php
Resolves #869 .
Wrong padding in file caused `ignored-entities` for comments to be handled incorrectly.
Reviewers:
Thank you.
=> Spam comment should not commit

plugins/versionpress/src/Database/WpdbMirrorBridge.php, plugins/versionpress/versionpress.php
Resolves #870.
We need at first change the storage and then the database because the DB update changes columns used in restriction.
Reviewers:
=> Removing menu item with children

plugins/versionpress/src/Storages/Serialization/IniSerializer.php, plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php, plugins/versionpress/tests/Unit/IniSerializerTest.php
Resolves #910.
IniSerializer now adds a simple prefix marker to all numbers in INI before parsing and removes it + restores the original type after parsing. 
Reviewers:
=> Numbers in INI are now handled correctly

plugins/versionpress/src/Api/VersionPressApi.php, plugins/versionpress/src/ChangeInfos/ChangeInfoEnvelope.php, plugins/versionpress/src/ChangeInfos/ChangeInfoMatcher.php
Resolves #895.
Manual commits now contain the environment, version of VP and overview displays changed INI files in `vpdb`.
Reviewers:
=> Missing environment when committing through VP admin

plugins/versionpress/tests/Utils/CommitAsserter.php
Resolves #895.
`CommitAsserter` caused failures in `GitRepositoryTests\RevertTest`. Additional condition fixes it.
Reviewers:
=> Fixed CommitAsserter 

gulpfile.js
Resolves #873.
I decided to create a separate `copy-without-build` task for `test-deploy`. Now the `gulp build` builds also the frontend and `gulp test-deploy` just copies the already built one. It's a small duplicity but I think it's OK.
Reviewers:
=> Build frontend on `gulp build`

plugins/versionpress/versionpress.php
Resolves #880 .
Please review also the discussion in issue #880 and add your ideas here.
Reviewers:
Thank you.
=> Display warning and disable activation when VersionPress not build correctly

plugins/versionpress/src/Cli/vp.php, plugins/versionpress/src/Git/GitConfig.php, plugins/versionpress/src/Git/GitRepository.php
Resolves #921.
All empty sections are now removed on commit and push. I also fixed a small bug in the `restore-site` command. I needed it for testing so it's part of this PR.
Reviewers:
=> Empty sections in `.git/config`

frontend/src/Commits/CommitsTable.less
Resolves #888.
Fixed environment z-index to be rendered above the checkbox.
Reviewers:
=> Uncommitted changes - CSS glitch for inactive select boxes

plugins/versionpress/tests/LoadTests/MergeDriverLoadTest.php
A quick PR without an issue.
MergeDriverLoadTest now executes almost instantly which is useful if someone runs the whole `tests` folder. To actually get some load test results, one needs to update the `ITERATIONS` constant in MergeDriverLoadTest which is probably fine because the results of this test need to inspected manually anyway.
Reviewers:
=> MergeDriverLoadTest is now fast by default

plugins/versionpress/src/Database/WpdbMirrorBridge.php, plugins/versionpress/src/Database/wordpress-schema.yml, plugins/versionpress/src/Storages/TermTaxonomyStorage.php, plugins/versionpress/src/Synchronizers/TermTaxonomiesSynchronizer.php, plugins/versionpress/tests/SynchronizerTests/Utils/EntityUtils.php, plugins/versionpress/tests/Utils/DBAsserter.php
Resolves #909.
`DbAsserter.php` now compares each column from database with value returned from `Storage`. Before this change if column from database was not found in storage it was skipped from any other processing. Implementing this issue has also 2 side effects : 
- ignoring of option `theme_switched`
- `false` values sent to *INSERT* or *UPDATE* query are now transformed to `""` (empty string)
Reviewers:
=> DbAsserter is more strict when comparing stored values against database

plugins/versionpress/src/Git/MergeDriverInstaller.php
Resolves #944.
The file `.git/config` may not exist if VersionPress wasn't fully activated. 
Reviewers:
=> Deactivating VP plugin before full activation causes warnings

docs/Testing.md, plugins/versionpress/tests/gulpfile.js
Resolves #936.
I split the original `run-tests` into two tasks – one for starting Selenium server, the second one for running the tests.
Reviewers:
=> Separate gulp task for Selenium

plugins/versionpress/src/ChangeInfos/VersionPressChangeInfo.php, plugins/versionpress/src/Git/MergeDriverInstaller.php, plugins/versionpress/tests/GitRepositoryTests/MergeDriverTest.php, plugins/versionpress/versionpress.php
Resolves #920.
- `.gitattributes` file is deleted when empty
- empty lines are not added to(left in) file
- if user change merge driver statement in `.gitattributes` to custom value, it is not replaced but new line with correct value is added.
Reviewers:
Thank you
=> Uninstall merge driver is not part of deactivation commit

plugins/versionpress/admin/inc/activate.php, plugins/versionpress/admin/inc/activationPanel.php, plugins/versionpress/admin/public/css/style.css, plugins/versionpress/src/Cli/vp.php, plugins/versionpress/src/Utils/WorkflowUtils.php, plugins/versionpress/tests/Workflow/WorkflowUtilsTest.php
Resolves #951.
There's a new piece of UI on the pre-activation screen:
The entered environment name is validated slightly in JavaScript (quick alert, nothing too fancy) and then on the server-side. If server-side validation fails, `default` is used as an env name (see #847).
Reviewers:
=> Set environment name before activation

plugins/versionpress/tests/End2End/Utils/PostTypeTestSeleniumWorker.php
Resolves #959.
Removed alert seem to not be present in selenium tests, so I've removed this test step.
Reviewers:
=> Unsaved post create draft

plugins/versionpress/tests/End2End/Utils/PostTypeTestSeleniumWorker.php
Done when working on #957 but does not really fix anything. The issue can be closed manually.
The new implementation does not depend on `sleep()`.
Reviewers:
=> Better implementation of `makeDraftFromUnsavedPost()`

plugins/versionpress/src/VersionPress.php
=> Default environment renamed to `default`

plugins/versionpress/src/Git/GitRepository.php, plugins/versionpress/src/Synchronizers/OptionsSynchronizer.php, plugins/versionpress/tests/End2End/Revert/IRevertTestWorker.php, plugins/versionpress/tests/End2End/Revert/RevertTest.php, plugins/versionpress/tests/End2End/Revert/RevertTestSeleniumWorker.php, plugins/versionpress/tests/End2End/Revert/RevertTestWpCliWorker.php
Resolves #972.
There was some change in the parameter of `synchronize` method comming from `Reverter` (empty array instead of null).
I will add some test for this. 
Reviewers:
=> Undo of manually changed file deletes options

plugins/versionpress/src/Cli/vp-internal.php, plugins/versionpress/src/Cli/vp.php
Resolves #977.
Synopsis is now generated from `## OPTIONS` section in `wp-cli` command description.
Reviewers:
=> Removal of @synopsis from PhpDocs

plugins/versionpress/src/Initialization/WpConfigSplitter.php, plugins/versionpress/src/Initialization/wp-config.common.tpl.php
Resolves #953.
`wp-config.common.php` now contains a comment that it has been added by VersionPress.
Reviewers:
=> `wp-config.common.php` commented

plugins/versionpress/tests/test-config.sample.yml
The default database host name in sample file was `localhost`. On Unix, this has a special meaning. For connections to `localhost`, MySQL programs attempt to connect to the local server by using a Unix socket file. To ensure that the client makes a TCP/IP connection to the local server, we set host name value to `127.0.0.1`. I've also changed default test site title to be more descriptive.
Please review: 
Thank you.
=> The default database host changed

plugins/versionpress/tests/Unit/TestConfigTest.php
In commit 3fce4c6 the default title of the site was changed to be more user friendly. However, `TestConfigTest.php` was testing `yaml` parsing which fails on searching old title in parsed data.
Please review:
Thank you.
=> Test of YAML parsing fixed after default page title was renamed

plugins/versionpress/tests/Unit/WpConfigSplitterTest.php
Resolves #953 .
When the test was run in test suite, it failed because `wp-config.ocmmon.tpl.php` was not found. Sorry for reopening.
=> Failing WpConfigSplitterTest

plugins/versionpress/src/Storages/Serialization/IniSerializer.php, plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php, plugins/versionpress/src/Utils/EntityUtils.php, plugins/versionpress/tests/Unit/IniSerializerTest.php
Resolves #1004 .
Null values are serialized as `<null>` and vice versa.
Reviewers:
=> Null values passed to serialization are replaced with <null>

plugins/versionpress/ruleset.xml
Resolves #1007.
By default, PHP Code Sniffer runs exclude-patterns against full paths which might be problematic e.g. when PhpStorm copies the project to a temporary location to run `phpcs` on it – suddenly, "temp" is in path and all the checks are skipped. With this change, all the paths are relative to where `phpcs` is executed, which is in the VersionPress plugin root (where `ruleset.xml` lives) both locally and on Travis.
Reviewers:
=> All paths in `ruleset.xml` are now relative

plugins/versionpress/src/Cli/vp.php, plugins/versionpress/src/DI/DIContainer.php, plugins/versionpress/src/Database/wordpress-schema.yml, plugins/versionpress/src/Initialization/Initializer.php
Resolves #1018, resolves #1013.
Fixed bugs related to cloning with WordPress in its own directory:
- Path detection in Initializer (causing wrong paths in `.gitignore`)
- Multiple usages of `get_site_url()` instead of `get_home_url()` (causing unreachable wp-admin)
- Wrong detection of path of `wp-config.php` on the clone (cloned site was using the same tables as original)
- VersionPress now tracks option `siteurl` (it is necessary to track it – it's the only information source about changed directory structure).
Reviewers:
=> Failing clone with WP in its own directory

plugins/versionpress/src/Utils/WpConfigEditor.php, plugins/versionpress/tests/Unit/WpConfigEditorTest.php
Resolves #1010.
The algorithm now tries to find a one-line comment containing exclamation mark (*stop editing!*, *ne touchez pas à ce qui suit !*, *Schluss mit dem Bearbeiten!*, *Это всё, дальше не редактируем. Успехов!*). If there is no such comment it tries to find `if ( !defined('ABSPATH') )` or `require_once(ABSPATH . 'wp-settings.php');`.
Reviewers:
=> Happy blogging

frontend/src/Commits/DiffPanel.react.tsx, frontend/src/common/DiffParser.ts
Resolves #1014.
Diff is now displayed also for empty text files
Reviewers:
=> Show diff for added and deleted empty text file

plugins/versionpress/setup-hooks.php, plugins/versionpress/src/Utils/WpConfigEditor.php, plugins/versionpress/uninstall.php
Resolves #1021 .
VersionPress constants are removed on uninstall. Also performed refactor of public constants (`VP_` prefixed)
Reviewers:
Thank you
=> Remove VP constants on deactivation

plugins/versionpress/src/Storages/Serialization/IniSerializer.php, plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php, plugins/versionpress/tests/Unit/IniSerializerTest.php
Resolves #1002 .
Also fix of incorrect computation of the string length when it contains newlines.
Reviewers:
Thank you.
=> Fixed deserialization when serialized string is starting with HTML tag

plugins/versionpress/src/Utils/FileSystem.php
Resolves #945
Reverts PR #1051 (I probably didn't test it properly) and improves the implementation of the `possiblyFixGitPermissions()` method so that it doesn't cause the permission bug reported in #945.
Reviewers:
=> .git permission fix for Windows

plugins/versionpress/ruleset.xml
=> Disabled CS rules for long lines and empty lines after beginning of a block 

plugins/versionpress/tests/Automation/WpAutomation.php
Resolves #1059
Added basic check that `<cached-WP-installation>/wp-settings.php` exists. If not, will re-download the WP version from wordpress.org.
Reviewers:
=> More reliable implementation of `WpAutomation::ensureCleanInstallationIsAvailable()`

frontend/package.json, frontend/src/BulkActionPanel/BulkActionPanel.react.tsx, frontend/src/CommitPanel/CommitPanel.react.tsx, frontend/src/Commits/CommitsTableRowDetails.react.tsx, frontend/src/Commits/CommitsTableRowSummary.react.tsx, frontend/src/ServicePanel/ServicePanel.react.tsx, frontend/src/common/FlashMessage.react.tsx, frontend/src/common/ProgressBar.react.tsx, frontend/src/pages/HomePage.react.tsx, frontend/typings.json
Resolves #1089.
Introduced [classnames](https://github.com/JedWatson/classnames) library to the front end codebase and improved readability and clarity of finding a string for the JSX attribute **className**.
Since @vasek17 is on vacation, I didn't include him as a reviewer of this PR.
Reviewers:
=> Use `classnames` library for complex class names

plugins/versionpress/src/Utils/SystemInfo.php
When executing GIT version check , the $process->getOutput() output would be correct _'git version 1.9.1'_ and $process->getErrorOutput() output would be **an empty string**, since no error was present. Currently it only verifies for NULL outputs, so the empty string would fail. 
BEFORE the fix : 
```
array (
'git-binary-as-configured' => 'git',
'git-available' => false,
'output' => 
array (
'stdout' => 'git version 1.9.1',
'stderr' => '',
),
'env-path' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
)
```
AFTER the fix: 
```
array (
'git-binary-as-configured' => 'git',
'git-available' => true,
'git-version' => '1.9.1',
'git-binary-as-called-by-vp' => 'git',
'git-full-path' => '/usr/bin/git
',
'versionpress-min-required-version' => '1.9',
'matches-min-required-version' …
```
=> Improved git verification on system info

frontend/src/actions/commits.ts, frontend/src/actions/update.ts, frontend/src/components/commits-table/CommitsTable.tsx, frontend/src/components/commits-table/commit-summary/CommitSummary.tsx, frontend/src/components/commits-table/environment/Environment.tsx, frontend/src/components/commits-table/header/Header.tsx, frontend/src/components/commits-table/row/Row.tsx, frontend/src/components/search/background/Background.less, frontend/src/components/search/modifiers/list/Component.tsx, frontend/src/components/search/modifiers/list/Item.tsx, frontend/src/components/search/modifiers/list/ItemHeader.tsx, frontend/src/stores/commitsTableStore.ts, frontend/src/stores/navigationStore.ts
Fixes some issues with integrating autocomplete (#805) and commit history visualisation (#1043) together:
- Visualisation is disabled when some search query is active
- Little visual tweaks
Reviewers:
=> Integration of autocomplete and commit history visualisation

plugins/versionpress/src/Cli/VPCommandUtils.php, plugins/versionpress/src/Cli/vp.php, plugins/versionpress/src/Git/GitRepository.php, plugins/versionpress/src/Utils/ProcessUtils.php, plugins/versionpress/src/Utils/RequirementsChecker.php, plugins/versionpress/src/Utils/SystemInfo.php, plugins/versionpress/tests/Automation/WpAutomation.php, plugins/versionpress/tests/End2End/Plugins/PluginsTest.php, plugins/versionpress/tests/SynchronizerTests/SynchronizerTestCase.php
Resolves #1132
Two main changes:
1. `ProcessUtils::escapeshellarg()` now always uses custom implementation and doesn't fall back to PHP's `escapeshellarg()`.
2. Changed all ocurrences of `escapeshellarg()` to `ProcessUtils::escapeshellarg()`. This was not strictly necessary but at least the escaping is now used consistently throughout the project.
Reviewers:
=> Custom `escapeshellarg()` implementation

plugins/versionpress/setup-hooks.php
This resolves a JS console error I was encountering on a theme that deregisters jQuery and re-registers it to run in the footer to defer jQuery loading. The dependency argument of wp_enqueue_script should be an array.
Reviewers:
=> Resolve JS console error if jQuery is in footer

plugins/versionpress/src/Utils/PathUtils.php, plugins/versionpress/tests/Unit/RelativePathsTest.php, plugins/versionpress/tests/test-config.sample.yml
Resolves #1158.
Makes `PathUtils::getRelativePath()` more permissive, updates Windows path example in test-config.sample.yml.
=> 1158 - relative paths on Windows fix

plugins/versionpress/src/Utils/AutocompleteUtils.php
Resolves #1196 
Tiny syntax fix.
=> AutocompleteUtils::capitalize() made static

plugins/versionpress/.versionpress/schema.yml
Resolves #1171
`sticky_posts` option added to `value-references` in `schema.yml`.
=> sticky_posts option added to value-references in schema.yml

plugins/versionpress/src/Utils/RequestDetector.php, plugins/versionpress/tests/End2End/Plugins/PluginsTest.php, plugins/versionpress/tests/End2End/Plugins/PluginsTestSeleniumWorker.php, plugins/versionpress/tests/End2End/Themes/ThemesTestSeleniumWorker.php
Resolves #1191
WP now sends multiple AJAX requests for bulk deleting plugins. There is no way we can recognize multiple quick manual clicks vs. bulk action. Therefore, VP makes a separate commit for every deleted plugin.
=> Deleting plugin or theme does not create a commit

plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php, plugins/versionpress/tests/Unit/IniSerializerTest.php, plugins/versionpress/tests/Unit/IniSerializer_FooClasses.php
Resolves #1224.
The field is now saved as e.g. `option_value["-Some\\Parent\\Class->attribute"] = "value"`.
=> Better format for parent's private fields in INI serializer

plugins/versionpress/.versionpress/actions.yml, plugins/versionpress/.versionpress/hooks.php, plugins/versionpress/src/Actions/ActionsInfo.php, plugins/versionpress/src/Git/ChangeInfoPreprocessors/TermTaxonomyPreprocessor.php, plugins/versionpress/src/Git/Committer.php
Resolves #1167 
The code in `TermTaxonomyPreprocessor` is only temporary – until #1123.
=> Missing value for VP-Term-Taxonomy

plugins/versionpress/bootstrap.php, plugins/versionpress/src/Cli/VPCommandUtils.php, plugins/versionpress/src/Cli/vp.php, plugins/versionpress/src/Initialization/Initializer.php, plugins/versionpress/src/Utils/SystemInfo.php, plugins/versionpress/src/Utils/WpConfigEditor.php, plugins/versionpress/tests/Automation/WpAutomation.php
Resolves #1186 
Creates new [config constant](https://docs.versionpress.net/en/getting-started/configuration#versionpress-config-constants) which gives an option to set custom path to [WP-CLI](http://wp-cli.org/). 
Works same way as _VP_GIT_BINARY_:
`wp vp config VP_WP_CLI_BINARY '/custom/path/to/wp'`
=> Added VP_WP_CLI_BINARY option to vp config

CONTRIBUTING.md, docs/Issues.md, docs/README.md
Minor change, moving the contents of [this wiki page (revision 46fbea)](https://github.com/versionpress/versionpress/wiki/Issues/46fbea68a58dcdb20983646e01c16c5801fc235d) to the repo and also updating the info on the issues we use.
=> Info on issues moved from wiki to repo

docs/content/en/01-getting-started/02-installation-uninstallation.md
Resolves #1200 
Required WordPress version bumped to 4.8. PHP stays on 5.6, Git on 1.9 but 2.13+ is now recommended.
No actual change in RequirementsChecker was necessary, just updated docs.
=> Revised system requirements for 4.0-beta

plugins/versionpress/src/Utils/WpConfigEditor.php, plugins/versionpress/tests/Unit/WpConfigEditorTest.php
Resolves #1107.
Here's a fix for the issue I opened with DB password that had regex characters in them not getting copied properly on initial clone.
Reviewers:
=> Fix for DB password with regex characters on initial clone.

plugins/versionpress/src/Cli/VPCommandUtils.php
Resolves #1049.
I think we can add the switch to all commands, no matter they were run under root or not. Commands running under standard user do not mind the `--allow-root` switch.
=> --allow-root for nested WP-CLI commands

plugins/versionpress/src/Database/VpidRepository.php
Resolves #1168
`$menuItemType` was changed and `$database->get_col` no longer returns `string` but `array`.
Some tests would be handy.
=> Fix conditions in getMenuReference()

plugins/versionpress/src/Utils/RequirementsChecker.php, plugins/versionpress/temp/.gitignore, plugins/versionpress/temp/security-check.txt
Resolves #1154 
We don't need the `temp` directory anymore: https://github.com/versionpress/versionpress/commit/6843b874b21fef3ea72f5e1958d40c871ecba213#diff-e8ccf25c798ea6d4068705426a027cdcR20
Security check in RequirementsChecker is now done against `versionpress-nginx.conf` (we need some non-interpreted text file).
=> Temp files in ZIP

gulpfile.js
ext-libs versions are locked since https://github.com/versionpress/versionpress/pull/1227/commits/fa1f6d33309e0c54cf1ed2ba017c5ea3e79d01a0, the Gulp task has been updated to respect this and not update on each run.
=> ext-libs are Composer-locked, not updated on each run

plugins/versionpress/tests/Automation/WpAutomation.php, plugins/versionpress/tests/docker-compose.yml
Ref: #1257 
The title says it all, just some experience from running a couple of tests:
- I've tried running `ActivationDeactivationTest` which was primarily blocked by the read-only approach and the tests ran. They failed on genuine Selenium issues like `Unable to locate element: .wrap form:nth-of-type(1) input#submit` which is probably due to a newer WordPress version and will be a separate PR.
- All End2End passed with the change.
- Sometimes, MySQL is not ready and tests fail with something like "cannot connect to MySQL server". The next run, when the docker-compose stack is up and running, passes fine.
=> VP is copied to a test site, no longer a read-only mount

plugins/versionpress/src/Cli/VPCommandUtils.php, plugins/versionpress/src/Cli/vp.php
Resolves #1279 
This was a tricky issue. There's probably a Symfony Process bug that sometimes converts an empty string argument to a single quote character, see: https://github.com/symfony/symfony/issues/23455.
The fix is to try to ensure that the important $args are the last ones. For example, if the main $args are `"DB_COLLATE"` and `""`, all the other args like `--color` and `--allow-root` are now prepended so that the final command reads like `wp vp update-config --color --allow-root "DB_COLLATE" ""`. In this order, everything works.
=> Fix for `wp vp update-config` and mysterious quote character instead of empty string

plugins/versionpress/src/Git/GitRepository.php
Resolves #1281 
[This](https://github.com/versionpress/versionpress/blob/8aa1e1f27ea18e596474d37432132632fb8b0d07/plugins/versionpress/src/Git/GitRepository.php#L84-L85) was returning an empty string instead of null on Windows under some circumstances. The fix is verified on both Windows and in Docker `Workflow` tests.
=> More reliable removing `user.name` and `user.email` from local Git config

plugins/versionpress/src/Cli/vp.php
Resolves #1313
The logging message is at the "error" level, because that's the logging level for doing "wp core download" a second time.
=> Added error when re-activating VP with WP CLI

docs/README.md
Docs README now recommends to put the deployed PR to a commit message of the `versionpress/docs.versionpress.net` repo.
=> Docs README small update

docs/content/en/getting-started/about-eap.md
No issue, small docs PR.
Made it clearer that developer preview should not be used in production, plus a mention of VersionPress.com as a production-ready alternative.
Also, I learned that ants can live for a very long time!
=> Updated docs page on Developer Preview

docs/content/en/developer/plugin-support.md
"Cache invalidation" was nested under "Ignoring entities", it's now at the same level, as is "Ignoring columns".
No issue, small PR.
=> Small fix of subheading nesting in plugin-support.md

.markdownlint.json, CONTRIBUTING.md, README.md, docs/README.md, docs/content/en/feature-focus/wp-cli.md, docs/content/en/getting-started/concepts.md, package-lock.json, package.json
This PR introduces [markdownlint](https://github.com/DavidAnson/markdownlint) to the project:
- New `npm run lint:markdown` script.
- Pre-commit hook that runs the linter on staged files only (thanks to [Husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged)).
- All markdownlint violations fixed (there were only a couple).
=> Use markdownlint for Markdown files

docs/README.md
Resolves #1367
The docs site is now automatically deployed to Netlify.
=> Deploying docs site to Netlify

plugins/versionpress/src/Database/VpidRepository.php
Resolves #1369 
This is a one liner to address the bug described in 1369.  With this change the INI file will contain a VP ID for "terms" instead of "term taxonomy".  This will align with the data Wordpress stores in the postmeta when a category navigation item is saved.
Here is a before/after comparison of the change as relates to the DB/INI data.
```
1. Add a Category to a menu in the admin area and save.
Wordpress inserts has the following data in the DB:
wp_postmeta
+---------+---------+------------------------+------------+
| meta_id | post_id | meta_key               | meta_value |
+---------+---------+------------------------+------------+
| 4471    |  2547   | _menu_item_object_id   | 46         |
+---------+---------+------------------------+------------+
wp_terms …
```
=> #1369 - updating getMenuReference to return "terms" instead of "term_taxonomy"

docker-compose.yml
z sets the SELinux labels so the docker containers can access those filesystem directories
On non-SELinux systems, the option does nothing.
Resolves:
The `npm` and `docker-compose` command documented in the README Dev-Setup currently don't work on SELinux systems (such as Fedora, which I'm using) because the docker containers cannot access the files in the volumes they're configured to mount. This PR fixes that.
See https://docs.docker.com/storage/bind-mounts/ for relevant documentation.
=> Set the "z" option for docker volumes

plugins/versionpress/src/Cli/vp-internal.php
Using require can cause the files being included once to result in an error as it does on Wordpress 5.1.
Resolves #1374
=> require_once the Wordpress includes

.travis.yml
The docker images all use PHP 7.2, so for consistency at least, Travis should also use PHP 7.2.
=> Use php7.2 in Travis to be consistent with the docker images

plugins/versionpress/admin/inc/activate.php, plugins/versionpress/admin/inc/admin.php, plugins/versionpress/composer.lock, plugins/versionpress/src/Utils/QueryLanguageUtils.php
Upgrade to the latest PHP_CodeSniffer (3.4.0). `( cd plugins/versionpress && ./vendor/bin/phpcs --standard=ruleset.xml )` then fails due to formatting issues; so fix those issues.
=> Upgrade to PHP_CodeSniffer and fix newly identified issues

.travis.yml
Have Travis run all tests:
- npm run lint:markdown
- npm run build-images
- npm run tests:full
- ( cd plugins/versionpress && ./vendor/bin/phpcs --standard=ruleset.xml )
With this improvement, tests are automatically run so no one has to manually do so. Tests are also run for all branches and PRs allowing for test passage to be a quality gate.
=> Run tests in Travis

plugins/versionpress/src/Git/merge-drivers/ini-merge.sh
=> Using "\" to escape "-" in tr isn't standard so move "-" to the end to avoid having to escape it

docker-compose.yml, plugins/versionpress/tests/End2End/Revert/RevertTest.php, plugins/versionpress/tests/Workflow/CloneMergeTest.php
On Debian, www-data:www-data is 33:33
On Alpine (which is what cli is based on), www-data:www-data is 82:82
Therefore, when Alpine and Debian interact, one has to change to match the other.
See https://github.com/docker-library/wordpress/issues/256 for details
Makes progress on #1383, Travis now gets further.
=> Run cli as user 33:33 to match www-data from versionpress/wordpress:php7.2-apache

docs/content/en/developer/dev-setup.md, docs/content/en/developer/testing.md
Small revision of content of Dev Setup and Testing pages after they have been separated in #1392.
Related issue: #1389 
Netlify previews:
- [Dev Setup](https://deploy-preview-1393--cranky-swanson-fd009e.netlify.com/en/developer/dev-setup/)
- [Testing](https://deploy-preview-1393--cranky-swanson-fd009e.netlify.com/en/developer/testing/)
=> Minor docs updates around dev setup and testing

.travis.yml
Reverts versionpress/versionpress#1381
I'm going to revert the Travis CI setup temporarily as all the builds fail right now (#1383) and it's not very useful to have CI running at this point. Quite to the contrary, e.g., Markdown changes that are fine are flagged as failed even though they're correct.
I'm going to describe how I'd imagine a good CI setup for us in a separate issue.
=> Revert "Run tests in Travis" for now

dev-env/wordpress-cli-image/Dockerfile, docker-compose-tests.yml
The CLI image is based on Alpine where the www-data user is UID 82 while the main WordPress image is based on Debian where www-data stands for UID 33. This causes trouble as files to `/var/www/html` are attempted to being read and written by different UIDs, depending on whether it's the Apache web server or WP-CLI / our testing code.
PR https://github.com/versionpress/versionpress/pull/1388 fixed the user on the `docker-compose.yml` level but that caused [this portion of Dockerfile](https://github.com/versionpress/versionpress/blob/618813bf79d9c2dc63bf5ebef751c84c46323130/dev-env/wordpress-cli-image/Dockerfile#L21-L32) to become invalid. This PR moves the solution to the Dockerfile level – it explicitly uses "33" instead of "www-data".
Some related resources:
- …
=> Run CLI image as UID 33 (Debian's "www-data")

dev-env/wordpress-cli-image/Dockerfile, dev-env/wordpress-image/Dockerfile, docker-compose-tests.yml, docker-compose.yml, package.json
Part of #1389 
The `docker-compose.yml` files now contain specific digests like this:
```yaml
services:
wordpress:
image: versionpress/wordpress:php7.2-apache@sha256:64b3c10adfef9ae65a140d5547d670d996c5c852b9a840c71a86a5be4f777fdc
```
Dockerfiles also lock specific versions:
```Dockerfile
FROM wordpress:cli@sha256:f8600f5df710c0973ed250e16c1286de7f8344cd8ce0dcba3779931010e956d4
```
This should lead to more predictable versions running on users' computers.
Implementation notes:
- `docker-compose config --resolve-image-digests` prints out docker-compose with digests resolved.
- Using `image:tag@sha` is a nice trick from [this article](https://renovatebot.com/blog/docker-mutable-tags) (that article is worth reading anyway!).
- (BTW, the article is by [Renovate](https://renovatebot.com), a …
=> Use digests for Docker images

docs/content/en/developer/dev-setup.md, package-lock.json, package.json, scripts/README.md, scripts/build.ts, scripts/init-dev.ts, scripts/init-phpstorm.ts, scripts/package-lock.json, scripts/package.json, scripts/script-utils.ts, scripts/tsconfig.json
Part of #1401 will be a `run-tests.ts` script for which I needed a bit updated `scripts` directory, which is done in this PR as it's a relatively separate work.
Main changes:
- The `scripts` folder is now a project with its own `package.json`. This allows to clearly state which dependencies are for scripts and which are global in the root `package.json` – not many are left there, see 4083e3513597c614cd864c5681ba556393c99a57.
- Also, `tsconfig.json` moved to `scripts`.
- Update all the dependencies after a while (no breaking changes, all went smoothly). d4936cfb5ac0e5e87055274b5b4990a4c227bf15
- All scripts can now be called from whichever `cwd` – they have been updated to contain paths relative to repo root explicitly. 273cd3371e35c6369e8cb1d79df3d82c2114b65c
=> 'Scripts' project with its own `package.json`, deps update

docs/content/en/developer/dev-setup.md
Part of #1389.
I'm verifying how `tests:full` run on Docker Toolbox for Windows, this PR documents the process.
See:
- My setup from clean Windows machine: https://github.com/versionpress/versionpress/pull/1403#issuecomment-473608973
- Updated docs: https://github.com/versionpress/versionpress/pull/1403/commits/a13ba8f96a0aa98cf5abe0047e45235778ce6367
=> Docker Toolbox on Windows – notes

plugins/versionpress/tests/Automation/WpAutomation.php, plugins/versionpress/tests/Workflow/CloneMergeTest.php
As a temporary solution for #1409, CloneMergeTest does a full site setup before it runs.
With the workaround in place, the full test suite passes for me 🎉 🎉 🎉 
This PR also update the behavior of `WpAutomation::setUpSite` in https://github.com/versionpress/versionpress/commit/eaa3b1bbcff8bb93eaf331239a8bb019627d6953 – the method now deletes any previous files.
=> Fresh site setup before CloneMergeTest

docs/content/en/developer/testing.md, package.json, scripts/run-tests.ts
Part of #1389
I wanted to get rid of the very slow copying of files between Docker volumes and the host OS (`npm run tests:copy-files-to-host`) via Samba as mentioned here: https://github.com/versionpress/versionpress/issues/1389#issuecomment-471550657. However, I couldn't make it work and it seems quite complex, see e.g. [this Reddit post](https://www.reddit.com/r/docker/comments/ai6cqr/please_help_me_with_the_dpersonsamba_container/).
So this PR is only about small improvements like introducing a new `--explore` option to `run-tests.ts` and updating the documentation.
One change in behavior is that `npm run tests:cleanup` now keep volumes. This has the advantage that `npm run tests -- --explore` can be run again when necessary; volumes are cleaned up when tests start. See …
=> Exploring the test stack – small updates

docs/content/en/troubleshooting/iis.md
@borekb simple change so markdownlint passes
=> Fix markdownlint violation in docs/content/en/troubleshooting/iis.md

.travis.yml, package.json
Issue: #1259
Travis will now run markdownlint, php codesniffer, build the docker images, and run the full tests.
With this change, VersionPress can now only merge PRs that have passing tests, ensuring that all tests always pass.
(This is a similar PR to #1381, after we have fixed the testing infrastructure in #1389 so that the tests actually pass.)
=> Have Travis run tests

scripts/run-tests.ts
An issue discovered in #1421. The `run-tests.ts` script now correctly forwards the exit code from the tests. Previously, the TypeScript script always returned `0` even if the tests failed – visually, the output was correct but Travis didn't see the build as failing.
A quick way to test this is to run `npm run tests:unit` with some unit test artificially failing. Before 7bd2f40, the exit code (`echo $?`) is zero, after it, it's `1`.
=> Fix `run-tests.ts`: return non-zero exit code when tests fail

CONTRIBUTING.md, docs/content/en/developer/development-process.md, docs/content/en/release-notes/index.md
Issue: #1417 
When preparing for the 4.0-beta2 release #1373 , I went through our docs on the development / release process and updated them slightly. It's been mostly deleting stuff:
- [Labels are now self-documenting](https://github.blog/2018-02-22-label-improvements-emoji-descriptions-and-more/) on GitHub.
- Note on imported issues 1..522 has been moved to https://github.com/versionpress/versionpress/issues/787#issuecomment-477146942.
- Info about release versioning has been duplicated between `developer/development-process.md` and `release-notes/index.md`, I simplified the Release Notes homepage.
=> Updated docs on development process

scripts/README.md, scripts/changelog.ts
Follow-up to #1424.
This PR adds the `--format markdown` flag which outputs full Markdown suitable for release notes and other such places.
=> Add `--format markdown` option to the `changelog` tool

docs/content/en/release-notes/4.0-beta2.md, docs/mkdocs.yml
Issue: #1373 
Using the `changelog` script for the first time.
Note that this PR will need to be merged before beta2 is released, making the full changelog in the release notes outdated by this single PR. So the common workflow will be to update the Markdown document post-release.
=> Add 4.0-beta2 release notes

docs/content/en/getting-started/about-eap.md
Small change, the title says it all.
=> Remove link to VersionPress.com from Developer Preview docs

plugins/versionpress/src/Utils/QueryLanguageUtils.php, plugins/versionpress/tests/Unit/EntityInfoTest.php
VersionPress doesn't correctly handled capitalized values in its schema configuration. The intent appears to be that comparison should be case insensitive, but that's not how it currently works.
For example, this configuration:
```
some-entity:
ignored-entities:
capitalized_value_field: VALUE
```
does not ignore this entity:
```
some-entity:
capitalized_value_field: VALUE
```
and it should.
=> Capitalized values aren't handled correctly

plugins/versionpress/tests/Unit/EntityInfoTest.php
Small follow-up after #1429.
The intention of two tests methods in `EntityInfoTest` was not clear, see https://github.com/versionpress/versionpress/pull/1429#pullrequestreview-231092304. I renamed the method names to hopefully be a bit clearer and added some comments.
=> Clarify names of tests in EntityInfoTest

plugins/versionpress/src/Database/SqlQueryParser.php, plugins/versionpress/tests/Unit/SqlQueryParserTest.php
Resolves #1436
For example, in query:
```
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('lines', 'First row\nSecond row\nThird row', 'yes')
```
the extracted value should be:
```
First row
Second row
Third row
```
But, before this change, due to the use of `stripcslashes`, the value would be:
```
First rownSecond rownThird row
```
=> Use stripcslashes instead of stripslashes when handling values in sql

plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php, plugins/versionpress/tests/Unit/IniSerializerTest.php
Resolves #1430 
Test cases have been described by @pavelevap in https://github.com/versionpress/versionpress/issues/1430#issuecomment-488575299, this PR adds them to tests and implements a fix.
Double serialized values like `serialize(serialize('some string'))` are now handled correctly.
=> Fix handling of values serialized multiple times

plugins/versionpress/tests/Workflow/CloneMergeTest.php
Issue: #1409 
Follow-up to #1410 and #1421 
After we decided not to merge changes of #1421, see https://github.com/versionpress/versionpress/pull/1421#issuecomment-492123692, this is a follow-up PR to fix some of the comments and bring over some of the relevant commits from #1421, namely:
- Do not replace line endings on cloned site https://github.com/versionpress/versionpress/commit/099faf7d9787fccbd97f6ece10c7d635690b8a83 (originally https://github.com/versionpress/versionpress/pull/1421/commits/f07b6a610fc1faa145942563ed04daca7213e4fa).
- ~~TODO: should we bring over https://github.com/versionpress/versionpress/pull/1421/commits/9a84e45b7a57346e341ddbcd67c2e466a576f8ed as well?~~ Nope, see https://github.com/versionpress/versionpress/pull/1448#issuecomment-492163039.
=> Update CloneMergeTest and related to finish #1409

plugins/versionpress/composer.json, plugins/versionpress/composer.lock, plugins/versionpress/src/Database/SqlQueryParser.php
VersionPress was using 3.4.0; the latest version is 4.3.1.
Based on the changelog, this seems like a good idea: https://github.com/phpmyadmin/sql-parser/blob/v4.3.1/CHANGELOG.md
=>  Update phpmyadmin/sql-parser to 4.3.1

plugins/versionpress/setup-hooks.php
I didn't like the default icon at the top for the admin menu. `dashicons-backup` (or any other preferred icon https://developer.wordpress.org/resource/dashicons/) might be better?
=> change default icon

docs/content/en/developer/plugin-support.md, plugins/versionpress/src/Utils/QueryLanguageUtils.php, plugins/versionpress/tests/Unit/EntityInfoTest.php, plugins/versionpress/tests/Unit/QueryLanguageUtilsTest.php
Issue: #1439 
This PR performs several refactoring around how we treat case (in)sensitivity in `QueryLanguageUtils` and related tests. It doesn't change the public behavior – both Git history searching and entity matching are still case **in**sensitive.
In fact, this PR improves the behavior a bit so that not only values are case insensitive but also fields. For example, `FIELD: value` now matches `['field' => 'value']` (or any other combination of letter casing).
> Note: This PR replaces #1444 where most of the refactorings started, however, it also changed the behavior of entity matching to be case sensitive which we decided against for now.
Details:
- Query parsing in `createRulesFromQueries` now maintains original letter casing. For example, `field: VALUE` will be parsed to `['field' …
=> Refactor case sensitivity in rule matching and commit searching, take 2

plugins/versionpress/setup-hooks.php
`automatic_updates_is_vcs_checkout` should return false as long as VersionPress is active allowing automatic updates
Whether the first commit in the git repo is a VP activation commit or not is irrelevant.
@borekb @pavelevap What do you think?
=> Always allow automatic updates

docs/content/en/sync/index.md
https://blog.versionpress.net/2015/09/versionpress-2-0-staging/ 
this url doesnt exist
found at https://versionpress.com/blog/2015/09/versionpress-2-0-staging/
=> fix broken link
